(function (global) {
  "use strict";

  const hardinessDict = {
    H1a: { temp: "> 15°C", cat: "Heated greenhouse - tropical", def: "Under glass all year." },
    H1b: { temp: "10 to 15°C", cat: "Heated greenhouse - subtropical", def: "Can be grown outside in summer in hotter, sunny, sheltered spots, but generally performs better under glass all year." },
    H1c: { temp: "5 to 10°C", cat: "Heated greenhouse - warm temperate", def: "Can be grown outside in summer throughout most of the UK while daytime temperatures are high enough." },
    H2: { temp: "1 to 5°C", cat: "Tender - cool or frost-free greenhouse", def: "Tolerant of low temperatures, but not surviving being frozen. Requires glasshouse protection except in frost-free inner-city or coastal areas." },
    H3: { temp: "-5 to 1°C", cat: "Hardy in coastal & mild areas", def: "Hardy in coastal and mild parts of the UK except in severe winters. At risk from sudden early frosts." },
    H4: { temp: "-10 to -5°C", cat: "Hardy - average winter", def: "Hardy through most of the UK apart from inland valleys, at altitude, and central/northerly locations. May suffer foliage damage in harsh winters." },
    H5: { temp: "-15 to -10°C", cat: "Hardy in most places", def: "Hardy in most places throughout the UK even in severe winters. May not withstand open/exposed sites or central/northern locations." },
    H6: { temp: "-20 to -15°C", cat: "Hardy - very cold winter", def: "Hardy in all of UK and northern Europe. Container-grown plants need root protection." },
    H7: { temp: "< -20°C", cat: "Very hardy", def: "Hardy in the severest European continental climates including exposed upland locations in the UK." }
  };

  const focusGroupIds = [11, 20, 1, 39, 56, 69, 91, 93, 95, 102, 107];

  const rhsPlantDatabase = [
    { id: 1, botanicalName: "× Cuprocyparis leylandii", commonName: "Leyland cypress", category: "Trees & Conifers", habit: "Large, fast-growing, dense evergreen conifer of columnar habit", heightSpread: "H: Higher than 12 metres | S: 4–8 metres", hardiness: "H6", light: "Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (well-drained)", uses: "Architectural; Hedging and screens", features: "Flattened sprays of scale-like evergreen foliage; very fast screening growth", nonCultivated: "Cultivated conifer", sourceUrl: "https://www.rhs.org.uk/plants/190606/x-cuprocyparis-leylandii/details" },
    { id: 4, botanicalName: "Acer griseum", commonName: "paperbark maple", category: "Trees & Conifers", habit: "Spreading deciduous tree", heightSpread: "H: 8–12 metres | S: 4–8 metres", hardiness: "H5", light: "Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "Architectural; Specimen tree; Smaller gardens", features: "Peeling cinnamon-brown bark and rich autumn colour", nonCultivated: "Cultivated tree", sourceUrl: "https://www.rhs.org.uk/plants/197/acer-griseum/details" },
    { id: 8, botanicalName: "Aesculus hippocastanum", commonName: "horse chestnut", category: "Trees & Conifers", habit: "Large spreading deciduous tree", heightSpread: "H: Higher than 12 metres | S: Wider than 8 metres", hardiness: "H6", light: "Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "Parkland; Large gardens; Wildlife gardens", features: "Palmate leaves, upright white flower panicles and conkers", nonCultivated: "Cultivated / naturalised tree", sourceUrl: "https://www.rhs.org.uk/plants/585/aesculus-hippocastanum/details" },
    { id: 9, botanicalName: "Agave americana", commonName: "century plant", category: "Cacti & Succulents", habit: "Rosette-forming evergreen succulent perennial", heightSpread: "H: 1–1.5 metres | S: 1–1.5 metres", hardiness: "H2", light: "Full sun", aspect: "South-facing, West-facing", pH: "Any", soil: "Loam, Sand (sharply drained)", uses: "Architectural; Patio and container plants; Conservatory", features: "Large spiny blue-green rosettes; monocarpic flower spike", nonCultivated: "Cultivated succulent", sourceUrl: "https://www.rhs.org.uk/plants/95075/agave-americana/details" },
    { id: 11, botanicalName: "Araucaria araucana", commonName: "monkey puzzle", category: "Trees & Conifers", habit: "Bushy architectural evergreen conifer", heightSpread: "H: Higher than 12 metres | S: Wider than 8 metres", hardiness: "H7", light: "Full sun, Partial shade", aspect: "East-facing, South-facing, West-facing", pH: "Any", soil: "Chalk, Loam, Sand (moist but well-drained)", uses: "Architectural", features: "Whorled branches clothed in sharply pointed triangular dark green leaves", nonCultivated: "Cultivated conifer", sourceUrl: "https://www.rhs.org.uk/plants/1456/araucaria-araucana/details" },
    { id: 12, botanicalName: "Arbutus unedo", commonName: "strawberry tree", category: "Trees & Conifers", habit: "Spreading evergreen shrubby tree", heightSpread: "H: 4–8 metres | S: 4–8 metres", hardiness: "H5", light: "Full sun", aspect: "South-facing, West-facing", pH: "Any", soil: "Chalk, Loam, Sand (well-drained)", uses: "Coastal; Mediterranean climate plants; City and courtyard gardens", features: "Rough red-brown bark, urn-shaped flowers and strawberry-like red fruits", nonCultivated: "Cultivated tree/shrub", sourceUrl: "https://www.rhs.org.uk/plants/1473/arbutus-unedo/details" },
    { id: 14, botanicalName: "Asplenium scolopendrium", commonName: "hart's tongue fern", category: "Ferns", habit: "Evergreen rosette-forming fern", heightSpread: "H: 0.1–0.5 metres | S: 0.1–0.5 metres", hardiness: "H6", light: "Full shade, Partial shade", aspect: "North-facing, East-facing, West-facing", pH: "Alkaline, Neutral", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "Woodland gardens; Ground cover; Shady borders", features: "Glossy undivided strap-like fronds", nonCultivated: "Native / cultivated fern", sourceUrl: "https://www.rhs.org.uk/plants/25910/asplenium-scolopendrium/details" },
    { id: 17, botanicalName: "Berberis darwinii", commonName: "Darwin's barberry", category: "Shrubs", habit: "Dense evergreen shrub", heightSpread: "H: 2.5–4 metres | S: 2.5–4 metres", hardiness: "H5", light: "Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "Hedging and screens; Security barriers; Wildlife gardens", features: "Spiny holly-like leaves, rich orange flowers and blue-black berries", nonCultivated: "Cultivated shrub", sourceUrl: "https://www.rhs.org.uk/plants/2105/berberis-darwinii/details" },
    { id: 20, botanicalName: "Buxus sempervirens", commonName: "common box", category: "Shrubs", habit: "Large bushy evergreen shrub or small tree", heightSpread: "H: 4–8 metres | S: 4–8 metres", hardiness: "H6", light: "Full shade, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained or well-drained)", uses: "City and courtyard gardens; Cottage and informal garden; Wildlife gardens; Patio and container plants; Hedging and screens", features: "Small glossy dark green leaves; clips well for topiary and formal hedging", nonCultivated: "Native / cultivated shrub", sourceUrl: "https://www.rhs.org.uk/plants/2579/buxus-sempervirens/details" },
    { id: 25, botanicalName: "Capsella bursa-pastoris", commonName: "shepherd's purse", category: "Non-cultivated plants (Weeds)", habit: "Annual or biennial rosette-forming weed", heightSpread: "H: up to 0.5 metres | S: variable", hardiness: "H7", light: "Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Bare and cultivated ground", uses: "Non-cultivated weed identification", features: "Tiny white flowers and distinctive heart-shaped seed pods", nonCultivated: "Non-cultivated annual/biennial weed", sourceUrl: "https://www.rhs.org.uk/plants/105534/capsella-bursa-pastoris/details" },
    { id: 27, botanicalName: "Choisya ternata", commonName: "Mexican orange blossom", category: "Shrubs", habit: "Rounded bushy evergreen shrub", heightSpread: "H: 1.5–2.5 metres | S: 1.5–2.5 metres", hardiness: "H4", light: "Full sun, Partial shade", aspect: "South-facing, East-facing, West-facing", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "City and courtyard gardens; Wall-side borders; Low maintenance", features: "Aromatic trifoliate leaves and fragrant white spring flowers", nonCultivated: "Cultivated shrub", sourceUrl: "https://www.rhs.org.uk/plants/3766/choisya-ternata/details" },
    { id: 28, botanicalName: "Clematis armandi", commonName: "Armand clematis", category: "Climbers & Wall Shrubs", habit: "Vigorous woody evergreen climber", heightSpread: "H: 4–8 metres | S: 1.5–2.5 metres", hardiness: "H4", light: "Full sun", aspect: "South-facing, West-facing", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "Wall-side borders; Fences and pergolas; Scented climber", features: "Glossy evergreen foliage and fragrant white spring flowers", nonCultivated: "Cultivated climber", sourceUrl: "https://www.rhs.org.uk/plants/3923/clematis-armandi/details" },
    { id: 29, botanicalName: "Clivia miniata", commonName: "Natal lily", category: "House plants", habit: "Clump-forming evergreen perennial", heightSpread: "H: 0.1–0.5 metres | S: 0.1–0.5 metres", hardiness: "H1c", light: "Partial shade", aspect: "Sheltered indoor light", pH: "Any", soil: "Loam-based potting compost (well-drained)", uses: "Houseplants; Conservatory and greenhouse", features: "Strap-like evergreen leaves and umbels of orange-red funnel-shaped flowers", nonCultivated: "Cultivated house plant", sourceUrl: "https://www.rhs.org.uk/plants/4036/clivia-miniata/details" },
    { id: 30, botanicalName: "Cordyline australis", commonName: "cabbage palm", category: "Trees & Conifers", habit: "Erect palm-like evergreen tree", heightSpread: "H: 4–8 metres | S: 2.5–4 metres", hardiness: "H3", light: "Full sun, Partial shade", aspect: "South-facing, East-facing, West-facing", pH: "Any", soil: "Chalk, Clay, Loam, Sand (well-drained)", uses: "Coastal; Architectural; City and courtyard gardens; Patio pots", features: "Sword-shaped leaves, palm-like silhouette and scented flower panicles", nonCultivated: "Cultivated tree", sourceUrl: "https://www.rhs.org.uk/plants/4361/cordyline-australis/details" },
    { id: 31, botanicalName: "Cornus sanguinea", commonName: "common dogwood", category: "Shrubs", habit: "Deciduous bushy shrub", heightSpread: "H: 1.5–2.5 metres | S: 1.5–2.5 metres", hardiness: "H6", light: "Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "Wildlife gardens; Hedges; Winter-stem displays", features: "Creamy white flowers, blue-black fruit and colourful winter stems", nonCultivated: "Native shrub", sourceUrl: "https://www.rhs.org.uk/plants/4408/cornus-sanguinea/details" },
    { id: 37, botanicalName: "Cyclamen hederifolium", commonName: "ivy-leaved cyclamen", category: "Bulbs, corms, rhizomes & tubers", habit: "Tuberous autumn-flowering perennial", heightSpread: "H: Up to 10 cm | S: 0.1–0.5 metres", hardiness: "H5", light: "Partial shade", aspect: "North-facing, East-facing, West-facing", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "Underplanting trees and shrubs; Rock gardens; Dry shade", features: "Marbled ivy-shaped leaves and reflexed pink or white flowers", nonCultivated: "Cultivated tuberous perennial", sourceUrl: "https://www.rhs.org.uk/plants/5145/cyclamen-hederifolium/details" },
    { id: 39, botanicalName: "Daphne bholua", commonName: "Nepalese paper plant", category: "Shrubs", habit: "Bushy evergreen or semi-evergreen shrub", heightSpread: "H: 1.5–2.5 metres | S: 1–1.5 metres", hardiness: "H4", light: "Full sun, Partial shade", aspect: "South-facing, West-facing, East-facing", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained or well-drained)", uses: "Cottage and informal garden; Flower borders and beds; Wall-side borders", features: "Very fragrant winter to early-spring flowers, white flushed purplish-pink", nonCultivated: "Cultivated shrub", sourceUrl: "https://www.rhs.org.uk/plants/5311/daphne-bholua/details" },
    { id: 41, botanicalName: "Dracaena trifasciata", commonName: "mother-in-law's tongue", category: "House plants", habit: "Clump-forming evergreen succulent perennial", heightSpread: "H: 1–1.5 metres | S: 0.1–0.5 metres", hardiness: "H1b", light: "Full sun, Partial shade", aspect: "Sheltered indoor light", pH: "Any", soil: "Loam, Sand (well-drained)", uses: "Houseplants; Conservatory and greenhouse", features: "Stiff upright sword-shaped variegated leaves", nonCultivated: "Cultivated house plant", sourceUrl: "https://www.rhs.org.uk/plants/16430/sansevieria-trifasciata/details" },
    { id: 43, botanicalName: "Elymus repens", commonName: "couch grass", category: "Non-cultivated plants (Weeds)", habit: "Fast-growing rhizomatous perennial grass", heightSpread: "H: up to 1.2 metres in flower | S: spreading by rhizomes", hardiness: "H7", light: "Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Lawns, borders, bare and cultivated ground", uses: "Non-cultivated weed identification", features: "Flat green leaves, upright flower spikes and pale spreading rhizomes", nonCultivated: "Native non-cultivated perennial weed", sourceUrl: "https://www.rhs.org.uk/plants/6342/elymus-repens/details" },
    { id: 44, botanicalName: "Erica × darleyensis", commonName: "Darley Dale heather", category: "Shrubs", habit: "Low evergreen heather shrub", heightSpread: "H: 0.1–0.5 metres | S: 0.5–1 metres", hardiness: "H5", light: "Full sun", aspect: "South-facing, West-facing", pH: "Any", soil: "Clay, Loam, Sand (moist but well-drained or well-drained)", uses: "Rock garden; Banks and slopes; Ground cover; Containers", features: "Needle-like foliage and winter to spring flowers", nonCultivated: "Cultivated hybrid shrub", sourceUrl: "https://www.rhs.org.uk/plants/search-results?query=Erica%20x%20darleyensis" },
    { id: 47, botanicalName: "Fagus sylvatica", commonName: "common beech", category: "Trees & Conifers", habit: "Large vigorous deciduous tree", heightSpread: "H: Higher than 12 metres | S: Wider than 8 metres", hardiness: "H6", light: "Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "Parkland; Large gardens; Hedging when clipped", features: "Smooth grey bark, broad crown and russet autumn foliage", nonCultivated: "Native tree", sourceUrl: "https://www.rhs.org.uk/plants/7127/fagus-sylvatica/details" },
    { id: 48, botanicalName: "Fatsia japonica", commonName: "Japanese aralia", category: "Shrubs", habit: "Bushy evergreen shrub", heightSpread: "H: 2.5–4 metres | S: 2.5–4 metres", hardiness: "H5", light: "Full shade, Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "Architectural; City and courtyard gardens; Shady borders", features: "Large glossy palmate leaves and late-season white flower clusters", nonCultivated: "Cultivated shrub", sourceUrl: "https://www.rhs.org.uk/plants/7147/fatsia-japonica/details" },
    { id: 52, botanicalName: "Griselinia littoralis", commonName: "New Zealand broadleaf", category: "Shrubs", habit: "Fast-growing large evergreen shrub", heightSpread: "H: 4–8 metres | S: 2.5–4 metres", hardiness: "H5", light: "Full sun", aspect: "South-facing, West-facing, East-facing", pH: "Any", soil: "Chalk, Clay, Loam, Sand (well-drained)", uses: "Coastal; Hedging and screens; Evergreen structure", features: "Light green oval leathery leaves and small yellow-green flowers", nonCultivated: "Cultivated shrub", sourceUrl: "https://www.rhs.org.uk/plants/8123/griselinia-littoralis/details" },
    { id: 53, botanicalName: "Hedera helix", commonName: "common ivy", category: "Climbers & Wall Shrubs", habit: "Evergreen self-clinging climber or groundcover", heightSpread: "H: 8–12 metres | S: 2.5–4 metres", hardiness: "H5", light: "Full shade, Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained or well-drained)", uses: "Ground cover; Wall cover; Wildlife habitats", features: "Evergreen juvenile and adult foliage; late flowers and black berries", nonCultivated: "Native climber", sourceUrl: "https://www.rhs.org.uk/plants/43091/hedera-helix/details" },
    { id: 55, botanicalName: "Helleborus × hybridus", commonName: "hybrid Lenten rose", category: "Perennials", habit: "Semi-evergreen herbaceous perennial", heightSpread: "H: 0.1–0.5 metres | S: 0.1–0.5 metres", hardiness: "H6", light: "Full sun, Partial shade", aspect: "Any", pH: "Alkaline, Neutral", soil: "Chalk, Clay, Loam (moist but well-drained)", uses: "Cottage and informal garden; Winter interest; Flower borders and beds", features: "Late winter to spring flowers above leathery leaves", nonCultivated: "Cultivated perennial", sourceUrl: "https://www.rhs.org.uk/plants/124882/helleborus-%C3%97-hybridus/details" },
    { id: 56, botanicalName: "Ilex aquifolium", commonName: "common holly", category: "Trees & Conifers", habit: "Large bushy evergreen tree", heightSpread: "H: Higher than 12 metres | S: 4–8 metres", hardiness: "H6", light: "Full sun, Partial shade", aspect: "South-facing, East-facing, West-facing", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained or well-drained)", uses: "Architectural; City and courtyard gardens; Coastal; Cottage and informal garden; Wildlife gardens; Hedging and screens", features: "Glossy spiny leaves, white spring flowers and red berries on pollinated female plants", nonCultivated: "Native tree", sourceUrl: "https://www.rhs.org.uk/plants/9087/ilex-aquifolium/details" },
    { id: 61, botanicalName: "Ligustrum ovalifolium", commonName: "garden privet", category: "Shrubs", habit: "Vigorous upright semi-evergreen or evergreen shrub", heightSpread: "H: 4–8 metres | S: 2.5–4 metres", hardiness: "H5", light: "Full sun", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (well-drained)", uses: "Hedging and screens; Urban gardens", features: "Oval glossy leaves, fragrant white midsummer flowers and black berries", nonCultivated: "Cultivated shrub", sourceUrl: "https://www.rhs.org.uk/plants/91966/ligustrum-ovalifolium/details" },
    { id: 62, botanicalName: "Liriope muscari", commonName: "big blue lilyturf", category: "Perennials", habit: "Tufted evergreen grass-like perennial", heightSpread: "H: 0.1–0.5 metres | S: 0.1–0.5 metres", hardiness: "H5", light: "Full shade, Partial shade", aspect: "North-facing, East-facing, West-facing", pH: "Acid, Neutral", soil: "Clay, Loam, Sand (moist but well-drained)", uses: "Ground cover; Underplanting roses and shrubs; Shady borders", features: "Arching leathery leaves and purple flower spikes in late summer/autumn", nonCultivated: "Cultivated perennial", sourceUrl: "https://www.rhs.org.uk/plants/10344/liriope-muscari/details" },
    { id: 69, botanicalName: "Monstera deliciosa", commonName: "Swiss cheese plant", category: "House plants", habit: "Evergreen climbing shrub with aerial roots", heightSpread: "H: 4–8 metres | S: 1.5–2.5 metres", hardiness: "H1b", light: "Partial shade", aspect: "South-facing", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "Sub-tropical; Houseplants; Conservatory and greenhouse", features: "Large glossy heart-shaped leaves, deeply cut and often perforated", nonCultivated: "Cultivated house plant", sourceUrl: "https://www.rhs.org.uk/plants/11192/monstera-deliciosa-f/details" },
    { id: 70, botanicalName: "Muscari armeniacum", commonName: "Armenian grape hyacinth", category: "Bulbs, corms, rhizomes & tubers", habit: "Bulbous perennial", heightSpread: "H: 0.1–0.5 metres | S: 0–0.1 metre", hardiness: "H6", light: "Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (well-drained)", uses: "Rock gardens; Containers; Spring bulb displays", features: "Narrow leaves and dense spikes of violet-blue spring flowers", nonCultivated: "Cultivated bulb", sourceUrl: "https://www.rhs.org.uk/plants/11247/muscari-armeniacum/details" },
    { id: 73, botanicalName: "Ophiopogon planiscapus", commonName: "mondo grass", category: "Perennials", habit: "Evergreen clump-forming grass-like perennial", heightSpread: "H: 0.1–0.5 metres | S: 0.1–0.5 metres", hardiness: "H5", light: "Full shade, Full sun, Partial shade", aspect: "Any", pH: "Acid, Neutral", soil: "Clay, Loam, Sand (moist but well-drained)", uses: "Underplanting; Ground cover; Garden edging; Rock garden; Containers", features: "Leathery strap-shaped leaves and small summer flowers followed by dark berries", nonCultivated: "Cultivated perennial", sourceUrl: "https://www.rhs.org.uk/plants/11839/ophiopogon-planiscapus/details" },
    { id: 77, botanicalName: "Phormium tenax", commonName: "New Zealand flax", category: "Shrubs", habit: "Robust evergreen clump-forming perennial", heightSpread: "H: 2.5–4 metres | S: 1.5–2.5 metres", hardiness: "H4", light: "Full sun, Partial shade", aspect: "South-facing, West-facing, East-facing", pH: "Acid, Neutral", soil: "Loam, Sand (moist but well-drained)", uses: "Architectural; Coastal; Containers; Sub-tropical planting", features: "Tall strap-shaped leaves and dull red tubular flowers on high panicles", nonCultivated: "Cultivated perennial/shrub", sourceUrl: "https://www.rhs.org.uk/plants/12791/phormium-tenax/details" },
    { id: 78, botanicalName: "Photinia × fraseri", commonName: "Christmas berry", category: "Shrubs", habit: "Evergreen shrub with colourful young growth", heightSpread: "H: 2.5–4 metres | S: 2.5–4 metres", hardiness: "H5", light: "Full sun, Partial shade", aspect: "South-facing, East-facing, West-facing", pH: "Any", soil: "Clay, Loam, Sand (moist but well-drained)", uses: "Hedging and screens; Mixed borders; Low maintenance", features: "Glossy leaves with bright red young growth and creamy-white spring flowers", nonCultivated: "Cultivated hybrid shrub", sourceUrl: "https://www.rhs.org.uk/plants/search-results?query=Photinia%20x%20fraseri" },
    { id: 79, botanicalName: "Phyllostachys aurea", commonName: "fish-pole bamboo", category: "Bamboos", habit: "Evergreen bamboo forming large clumps and sometimes spreading", heightSpread: "H: 4–8 metres | S: 2.5–4 metres", hardiness: "H5", light: "Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Clay, Loam, Sand (moist but well-drained)", uses: "Screening; Architectural; Tropical effect", features: "Bright green canes becoming yellowish with age and exposure", nonCultivated: "Cultivated bamboo", sourceUrl: "https://www.rhs.org.uk/plants/75274/phyllostachys-aurea/details" },
    { id: 80, botanicalName: "Pittosporum tenuifolium", commonName: "tawhiwhi", category: "Shrubs", habit: "Evergreen shrub or small tree", heightSpread: "H: 4–8 metres | S: 2.5–4 metres", hardiness: "H4", light: "Full sun, Partial shade", aspect: "South-facing, East-facing, West-facing", pH: "Any", soil: "Chalk, Loam, Sand (well-drained)", uses: "Coastal; Hedging and screens; Evergreen structure", features: "Small wavy leaves, dark stems and honey-scented dark flowers", nonCultivated: "Cultivated shrub", sourceUrl: "https://www.rhs.org.uk/plants/13202/pittosporum-tenuifolium/details" },
    { id: 85, botanicalName: "Prunus serrula", commonName: "Tibetan cherry", category: "Trees & Conifers", habit: "Round-headed small deciduous tree", heightSpread: "H: 8–12 metres | S: Wider than 8 metres", hardiness: "H6", light: "Full sun", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained or well-drained)", uses: "Cottage and informal garden; Wildlife gardens; Flower borders and beds", features: "Shining coppery-brown bark, white spring flowers and yellow autumn leaves", nonCultivated: "Cultivated tree", sourceUrl: "https://www.rhs.org.uk/plants/14025/prunus-serrula/details" },
    { id: 87, botanicalName: "Quercus robur", commonName: "common oak", category: "Trees & Conifers", habit: "Large deciduous tree with broad crown", heightSpread: "H: Higher than 12 metres | S: Wider than 8 metres", hardiness: "H6", light: "Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "Large gardens; Parkland; Wildlife gardens; Low maintenance", features: "Lobed leaves, catkins and acorns; major wildlife value", nonCultivated: "Native tree", sourceUrl: "https://www.rhs.org.uk/plants/14294/quercus-robur/details" },
    { id: 91, botanicalName: "Salvia rosmarinus", commonName: "rosemary", category: "Shrubs", habit: "Bushy evergreen aromatic shrub", heightSpread: "H: 1.5–2.5 metres | S: 1.5–2.5 metres", hardiness: "H4", light: "Full sun", aspect: "South-facing, West-facing", pH: "Any", soil: "Chalk, Loam, Sand (well-drained)", uses: "Patio and container plants; Rock garden; City and courtyard gardens; Coastal; Cottage and informal garden; Mediterranean climate plants; Gravel garden; Wildlife gardens; Flower borders and beds; Wall-side borders; Hedging and screens", features: "Aromatic linear leaves with pale undersides and pale violet-blue spring/summer flowers", nonCultivated: "Cultivated culinary shrub", sourceUrl: "https://www.rhs.org.uk/plants/384211/salvia-rosmarinus-ro/details" },
    { id: 93, botanicalName: "Sarcococca confusa", commonName: "sweet box", category: "Shrubs", habit: "Bushy evergreen shrub", heightSpread: "H: 1–1.5 metres | S: 1–1.5 metres", hardiness: "H5", light: "Full shade, Partial shade", aspect: "West-facing, East-facing, North-facing", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "City and courtyard gardens; Cottage and informal garden; Wildlife gardens; Hedging and screens", features: "Glossy dark leaves, very sweetly scented winter flowers and black berries", nonCultivated: "Cultivated shrub", sourceUrl: "https://www.rhs.org.uk/plants/16452/sarcococca-confusa/details" },
    { id: 94, botanicalName: "Sempervivum arachnoideum", commonName: "cobweb houseleek", category: "Alpines", habit: "Mat-forming evergreen succulent rosettes", heightSpread: "H: Up to 10 cm | S: 0.1–0.5 metres", hardiness: "H7", light: "Full sun", aspect: "South-facing, West-facing", pH: "Any", soil: "Loam, Sand (well-drained)", uses: "Rock garden; Containers; Alpine collections", features: "Small fleshy rosettes webbed with fine hairs and pink starry flowers", nonCultivated: "Cultivated alpine succulent", sourceUrl: "https://www.rhs.org.uk/plants/17075/sempervivum-arachnoideum/details" },
    { id: 95, botanicalName: "Skimmia japonica", commonName: "Japanese skimmia", category: "Shrubs", habit: "Bushy evergreen shrub", heightSpread: "H: 1.5–2.5 metres | S: 1–1.5 metres", hardiness: "H5", light: "Full shade, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Loam, Sand (moist but well-drained)", uses: "Cottage and informal garden; City and courtyard gardens; Wildlife gardens; Flower borders and beds; Hedging and screens", features: "Aromatic leathery leaves, fragrant spring flowers and red fruits on fertilised female plants", nonCultivated: "Cultivated shrub", sourceUrl: "https://www.rhs.org.uk/plants/17401/skimmia-japonica/details" },
    { id: 96, botanicalName: "Spathiphyllum wallisii", commonName: "Wallis peace lily", category: "House plants", habit: "Evergreen clump-forming herbaceous perennial", heightSpread: "H: 0.1–0.5 metres | S: 0.1–0.5 metres", hardiness: "H1b", light: "Partial shade", aspect: "Sheltered indoor light", pH: "Acid, Neutral", soil: "Chalk, Loam, Sand (moist but well-drained)", uses: "Houseplants; Conservatory and greenhouse", features: "Glossy lance-shaped leaves and white spathes around cream spadices", nonCultivated: "Cultivated house plant", sourceUrl: "https://www.rhs.org.uk/plants/17623/spathiphyllum-wallisii/details" },
    { id: 102, botanicalName: "Taxus baccata", commonName: "common yew", category: "Trees & Conifers", habit: "Bushy evergreen conifer tree or large shrub", heightSpread: "H: Higher than 12 metres | S: Wider than 8 metres", hardiness: "H7", light: "Full shade, Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (well-drained)", uses: "Hedging and screens", features: "Dark green needle-like foliage and red arils on female plants; toxic if eaten", nonCultivated: "Native tree", sourceUrl: "https://www.rhs.org.uk/plants/18001/taxus-baccata/details" },
    { id: 107, botanicalName: "Viburnum davidii", commonName: "David viburnum", category: "Shrubs", habit: "Small spreading evergreen shrub", heightSpread: "H: 1–1.5 metres | S: 1–1.5 metres", hardiness: "H5", light: "Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained or well-drained)", uses: "Underplanting of roses and shrubs; Ground cover", features: "Three-veined leathery evergreen leaves, white flowerheads and metallic blue-black berries on cross-pollinated plants", nonCultivated: "Cultivated shrub", sourceUrl: "https://www.rhs.org.uk/plants/18892/viburnum-davidii/details" },
    { id: 108, botanicalName: "Vinca major", commonName: "greater periwinkle", category: "Perennials", habit: "Spreading evergreen herbaceous perennial/subshrub", heightSpread: "H: 0.1–0.5 metres | S: 1.5–2.5 metres", hardiness: "H5", light: "Full shade, Full sun, Partial shade", aspect: "Any", pH: "Any", soil: "Chalk, Clay, Loam, Sand (moist but well-drained)", uses: "Ground cover; Banks and slopes; Shady borders", features: "Arching shoots, glossy leaves and violet-blue flowers", nonCultivated: "Naturalised perennial", sourceUrl: "https://www.rhs.org.uk/plants/18969/vinca-major/details" },
    { id: 110, botanicalName: "Zamioculcas zamiifolia", commonName: "Zanzibar gem", category: "House plants", habit: "Evergreen rhizomatous houseplant", heightSpread: "H: 0.5–1 metres | S: 0.5–1 metres", hardiness: "H1a", light: "Full shade, Partial shade", aspect: "Sheltered indoor light", pH: "Acid, Neutral", soil: "Loam, Sand (well-drained)", uses: "Houseplants; Conservatory and greenhouse", features: "Glossy upright pinnate leaves and excellent tolerance of indoor shade", nonCultivated: "Cultivated house plant", sourceUrl: "https://www.rhs.org.uk/plants/19185/zamioculcas-zamiifolia/details" }
  ];

  const payload = { hardinessDict, focusGroupIds, rhsPlantDatabase };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = payload;
  }

  global.RHSPlantData = payload;
})(typeof window !== "undefined" ? window : globalThis);
